<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <PropertyGroup>
    <Authors>craftworkgames</Authors>
    <Description>It makes MonoGame more awesome.</Description>
    <PackageTags>monogame extended pipeline bmfont tiled texture atlas input viewport fps shapes sprite</PackageTags>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <PropertyGroup>
    <NoWarn>NU1701</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MonoGame.Framework.DesktopGL.9000" Version="3.11.9002">
      <PrivateAssets>All</PrivateAssets>
    </PackageReference>
    <PackageReference Include="nkast.Xna.Framework.Content.Pipeline" Version="3.11.9002">
      <PrivateAssets>All</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
  </ItemGroup>

</Project>
